---
title: "Pontes Aéreas"
output: html_notebook
---

```{r}
# Pacotes -----------------------------------------------------------------

library(tidyverse)
library(nycflights13)

```

```{r}
# Base de dados -----------------------------------------------------------

data(flights)
data(airports)

# Dados ----------------------------------------------------------------------------------------------------

flights <- flights %>% select(origin, dest)
airports <- airports %>% select(faa, lat, lon)

flights_com_lat_lon <- flights %>%
  left_join(airports, by = c("origin" = "faa")) %>%
  rename(lat_origin = lat, lon_origin = lon) %>%
  left_join(airports, by = c("dest" = "faa")) %>%
  rename(lat_dest = lat, lon_dest = lon) %>%
  mutate(ordered_pair = if_else(origin > dest, paste0(dest, origin), paste0(origin, dest))) %>%
  tidyr::drop_na() %>%
  dplyr::distinct()

```


```{r}
# Base do mapa ----------------------------------------------------------------------------------------------------
mapa <- map_data("world") #poligonos do mapa

base_do_mapa <- mapa %>% 
  ggplot(aes(x = long, y = lat, group = group)) +
  geom_polygon(fill = "black", color = "white", size=0.15) +
  theme_void() +
  theme(plot.background = element_rect(fill = "black"), legend.position = "none") +
  coord_equal(xlim = range(flights_com_lat_lon$lon_dest), ylim = range(flights_com_lat_lon$lat_dest)) 
```


```{r}
# origens e destinos -----------------------------------------------------------------------------------------------  

base_do_mapa +
  geom_point(
    data = flights_com_lat_lon, 
    aes(x = lon_dest, y = lat_dest), 
    alpha=0.25, 
    size=1,
    color = "red", 
    inherit.aes = FALSE
  ) +
  geom_point(
    data = flights_com_lat_lon, 
    aes(x = lon_origin, y = lat_origin), 
    alpha=0.25, 
    size=3,
    color = "green", 
    inherit.aes = FALSE
  )
```


```{r}
# pontes aereas ----------------------------------------------------------------------------------------------------  

base_do_mapa +
  geom_curve(
    data = flights_com_lat_lon, 
    aes(x = lon_origin, xend = lon_dest, y = lat_origin,  yend = lat_dest), 
    alpha=0.25, 
    size=0.1,
    color = "purple", 
    inherit.aes = FALSE
  )
```

```{r}
# referência -------------------------
# https://sjfox.github.io/post/world_map_flights/
```



