---
title: "Dashboard de vôos"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(ggridges)
library(nycflights13)

flights <- flights %>% filter(month == 1)
```

Visão geral
======================================================================

Row {data-height=110}
----------------------------------------------------------------------

### O objetivo

Visualizar dados relacionados aos vôos que ocorreram em Nova York durante
o ano de 2013 procurando entender a relação entre os atrasos, o clima e
outras variáveis.

Row
-----------------------------------------------------------------------

### # vôos

```{r}
valueBox(
  scales::comma(nrow(flights), big.mark = ".", decimal.mark = ","), 
  icon = "fa-fighter-jet"
)
```

### # destinos

```{r}
valueBox(
  scales::comma(n_distinct(flights$dest), big.mark = ".", decimal.mark = ","), 
  icon = "fa-warehouse"
)
```

### # companhias aéreas

```{r}
valueBox(
  scales::comma(n_distinct(flights$carrier), big.mark = ".", decimal.mark = ","), 
  icon = "fa-random"
)
```

Row
--------------------------------------------------------------

### Quantidade de vôos por mês

```{r}
p <- flights %>% 
  mutate(data = ymd(paste(year, month, day))) %>% 
  group_by(month(data)) %>% 
  summarise(n = n(), data = min(data)) %>% 
  ggplot(aes(x = data, y = n)) +
  geom_col(fill = "lightblue") +
  theme_minimal() +
  labs(x = "Data", y = "# de Vôos")
plotly::ggplotly(p)
```

> Quantidade de vôos bem parecida durante todo o ano. Nada muito diferente para notar.

### Vôos por dia da semana

```{r}
p <- flights %>% 
  mutate(data = ymd(paste(year, month, day))) %>% 
  group_by(dds = wday(data, label = TRUE)) %>% 
  summarise(n = n()) %>% 
  ggplot(aes(x = dds, y = n)) +
  geom_col(fill = "lightblue") +
  theme_minimal() +
  labs(x = "Data", y = "# de Vôos")
plotly::ggplotly(p)
```

> Durante a semana os vôos são distribuidos parecidamente, exceto pelo final de 
semana onde acontecem menos vôos.


Companhias Aéreas
==============================================================

Row
---------------------------------------------------------------

### Companhias aéreas e atrasos

```{r}
p <- flights %>% 
  group_by(carrier) %>% 
  summarise(prop_delay = mean(arr_delay > 30, na.rm = TRUE)) %>% 
  ggplot(aes(y = prop_delay, x = carrier)) + 
  geom_segment( aes(x=fct_reorder(carrier, prop_delay), xend=carrier, y=0, yend=prop_delay), color="black") +
  geom_point(color="blue", size=4) +
  coord_flip() +
  theme_minimal() +
  scale_y_continuous(labels = scales::percent) + 
  labs(y = "Proporção de vôos em atraso", x = "Companhia Aérea")
plotly::ggplotly(p)
```

> Consideramos como atrasos os vôos que chegaram pelo menos 30 minutos depois
da data hora prevista de chegada.

### Distribuição dos atrrasos

```{r}
p <- flights %>% 
  filter(dep_delay > 30) %>% 
  ggplot(aes(x = fct_reorder(carrier, dep_delay), y = dep_delay)) +
  geom_boxplot(outlier.shape = NA) +
  coord_flip(ylim = c(30, 300)) +
  theme_minimal()
plotly::ggplotly(p)
```

> Vemos que os filmes de animação tem a maior chance de "estourar" seguidos por aventura e ação.

